# Generated by Django 5.0.2 on 2024-05-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='node42_auth_level',
            field=models.IntegerField(choices=[(0, 'Guest'), (2, 'Charter'), (4, 'Host'), (8, 'Admin'), (1024, 'Sudo')], default=0, verbose_name='身份'),
        ),
    ]
