# Generated by Django 5.0.2 on 2024-05-15 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0003_customuser_avatar_customuser_bio_customuser_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='admin_verification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_verification',
            field=models.BooleanField(default=False),
        ),
    ]
