# Generated by Django 5.0.2 on 2024-05-16 13:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(max_length=150)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.competition')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('value', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.stage')),
            ],
        ),
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField(blank=True, max_length=150)),
                ('chartfile', models.FileField(blank=True, upload_to='charts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
                ('stage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='competition.stage')),
            ],
        ),
        migrations.CreateModel(
            name='StageAction',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('action', models.CharField(choices=[('init', 'init'), ('pre', 'prepare'), ('chart', 'chart making'), ('judge', 'chart judge'), ('end', 'end')], default='init', max_length=20, verbose_name='比賽阶段')),
                ('stage_action_permission', models.JSONField(default=dict)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.stage')),
            ],
        ),
        migrations.CreateModel(
            name='StageResource',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('background', models.ImageField(blank=True, null=True, upload_to='background/', verbose_name='背景')),
                ('music', models.FileField(upload_to='music/', verbose_name='音乐')),
                ('chart_template', models.FileField(blank=True, null=True, upload_to='chart_template/', verbose_name='谱面模板')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.stage')),
            ],
        ),
        migrations.CreateModel(
            name='StageResourceMetadata',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('song_name', models.TextField(max_length=150)),
                ('artist', models.TextField(max_length=150)),
                ('illustrator', models.TextField(blank=True, max_length=150)),
                ('difficulty_range', models.TextField(blank=True, max_length=50)),
                ('source', models.TextField(blank=True, max_length=150)),
                ('genre', models.TextField(blank=True, max_length=150)),
                ('beat', models.TextField(blank=True)),
                ('bpm', models.TextField(blank=True)),
                ('resource', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='competition.stageresource')),
            ],
        ),
        migrations.CreateModel(
            name='UserCompetitionRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('spectator', 'Spectator'), ('participant', 'Participant'), ('judge', 'Judge'), ('host', 'Host'), ('owner', 'Owner')], max_length=50)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.stage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'stage', 'role')},
            },
        ),
    ]
