name: deploy
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands to develop
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.MK1_HOST }}
          username: ${{ secrets.MK1_USER }}
          port: ${{ secrets.MK1_SSHPORT }}
          key: ${{ secrets.MK1_SSHPUB }}
          password: ${{ secrets.MK1_SSHPWD }}
          script: |
            cd  ${{ secrets.MK1_BACKEND_PATH }} 
            git pull
            sudo sh start.sh
